app:
  sqlite:
    path: ${SQLITE_PATH}
  mssql:
    url: "jdbc:sqlserver://${MSSQL_HOST:10.10.10.10}:${MSSQL_PORT:1433};databaseName=${MSSQL_DB:Logs1C};encrypt=false;trustServerCertificate=true;sslProtocol=TLSv1;"
    username: ${MSSQL_USER:sa}
    password: ${MSSQL_PASS:password}
  migration:
    batch-size: ${BATCH_SIZE:1000}
    interval-ms: ${INTERVAL_MS:60000}
    delete-after-sync: ${DELETE_AFTER_SYNC:false}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

spring:
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false
  sql:
    init:
      mode: always
      platform: mssql
      encoding: UTF-8
  datasource:
    url: ${app.mssql.url}
    username: ${app.mssql.username}
    password: ${app.mssql.password}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

logging:
  level:
    com.microsoft.sqlserver.jdbc.internals.TDS.Channel: ERROR